[project]
name = "leson-10-3"
version = "0.1.0"
description = ""
authors = [
    {name = "Luybov",email = "kalna.lyubov2017@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "leson_10"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
